### ISSUE TITLE
removeAll resets the state to its initial value instead of removing all entities

### ISSUE THREAD

**Issue by krtek4** [Angular-RU/angular-ru-sdk#1128]
From the documentation :

> state.removeAll() | void | Remove all entities from the collection

But if we look at the code :

```
    @DataAction()
    public removeAll(): void {
        this.setEntitiesState(this.initialState);
    }
```

My understanding is that "Remove all entities from the state" will only clear the entities attribute of the state and not reset the state to its initial value.

Also, this is misleading if the initialState contains entities, `removeAll` would then "leave" entities in the state.

**Comment by krtek4** [comment]
I recreated this from https://github.com/ngxs-labs/data/issues/647 since it wasn't migrated here

**Comment by splincode** [comment]
https://github.com/Angular-RU/angular-ru-sdk/issues/861

**Comment by splincode** [comment]
@krtek4 you can help us, welcome to create PR

**Comment by krtek4** [comment]
> #861

Yes sorry, saw that afterward, but it didn't show when I searched for `removeAll`

> @krtek4 you can help us, welcome to create PR

Here you go : https://github.com/Angular-RU/angular-ru-sdk/pull/1129 (sorry it don't match any guidelines, but it's a one line change :) )
