### ISSUE TITLE
🚀 - Make some CDK directive switchable

### ISSUE THREAD

**Issue by Schirbak** [Angular-RU/angular-ru-sdk#1137]
### Which @angular-ru/* package(s) are relevant/releated to the feature request?

cdk

### Description

Allow several directives, that usually are applying to the inputs and **don't** changes the data type, to be switchable. Such directives include TrimInput, InitialFocus and InputFilter. An example of a directive that, on the contrary, **changes** the data type is the SplitString.

So the goal is to provide the input that allows to enable/disable the directive's behavior, like it's already made in the Tooltip directive:
```ts
@Directive({ selector: '[tooltip]' })
export class TooltipDirective implements OnDestroy {
    // ...
    @Input('tooltip-disabled') public tooltipDisabled!: boolean;
    // ...
}
```

It allows to use them in autogen or in the inputs that plays several roles simultaneously (e.g. the input that can change bounded form control key by selection, img below). 

<img width="266" alt="Снимок экрана 2021-12-07 в 13 04 34" src="https://user-images.githubusercontent.com/33288503/145008745-9d115846-d07c-45fb-9406-de4e4d96f2e1.png">

**Comment by Schirbak** [comment]
@splincode wyt?

**Comment by splincode** [comment]
@Schirbak Great idea, go ahead
