### ISSUE TITLE
🚀 - make it possible to use `isolatedModules` in client code

### ISSUE THREAD

**Issue by Schirbak** [Angular-RU/angular-ru-sdk#1387]
### Which @angular-ru/* package(s) are relevant/releated to the feature request?

typescript

### Description

Currently, you cannot use the `isolatedModules` property in client code when compiling if any enum from Angular-ru package is used. As you know, this property can [only be used when `preserveConstEnums` is enabled](https://www.typescriptlang.org/tsconfig#isolatedModules), and in these packages it is intentionally disabled. For example, enum `RoundingModes` — the following error is displayed:
> Cannot read properties of undefined (reading 'HALF_UP').

Thus, for example, the `isolatedModules` property in the `createTsJestConfig` function becomes useless, since it cannot be enabled using entities from a neighboring Angular-ru package.

I propose to enable `preserveConstEnums` for the buildable/publishable libraries, because whether it reaches the browser as an object or not is decided not at this level, but at the level of the application project. And the `isolatedModule` property can be useful for passing jest tests quickly.

**Comment by Schirbak** [comment]
@splincode what do you think?

**Comment by splincode** [comment]
@Schirbak No problem, go ahead

**Comment by Schirbak** [comment]
By the way, for future generations, there is an interesting workaround. In jest, a module that does not contain the necessary entities [can be mocked](https://jestjs.io/docs/manual-mocks). In this case, create a file `__mocks__/@angular-ru/cdk/big-decimal.ts` with the following content:
```ts
export * from '@angular-ru/cdk/big-decimal';

export const enum RoundingModes {
    CEILING = 0,
    // ... and the rest of `RoundingModes`
}
```
Checked it works. But I will still include the property.

**Comment by splincode** [comment]
> But I will still enable the property.

No problem
