### ISSUE TITLE
🐞 - Error while compiling the app

### ISSUE THREAD

**Issue by bphkns** [Angular-RU/angular-ru-sdk#1459]
### Which @angular-ru/* package(s) are the source of the bug?

ngxs

### Is this a regression?

Yes

### Description

Error while running app

`./node_modules/.pnpm/@angular-ru+ngxs@14.1.1/node_modules/@angular-ru/ngxs/fesm2020/angular-ru-ngxs-internals.mjs:103:75-93 - Error: export 'NGXS_STATE_FACTORY' (imported as 'NGXS_STATE_FACTORY') was not found in '@ngxs/store/internals' (possible exports: INITIAL_STATE_TOKEN, InitialState, NgxsBootstrapper, isAngularInTestMode, memoize, ɵNGXS_STATE_CONTEXT_FACTORY, ɵNGXS_STATE_FACTORY)`

Versions
    ```
   dependencies":  {
      "@angular-ru/cdk": "14.10.1",
      "@angular-ru/ngxs": "14.1.1",
      "@angular/animations": "15.2.5",
      "@angular/cdk": "15.2.5",
      "@angular/common": "15.2.5",
      "@angular/compiler": "15.2.5",
      "@angular/core": "15.2.5"
    },
    "devDependencies":  {
        "@angular-builders/custom-webpack": "15.0.0-beta.0",
        "@angular-devkit/build-angular": "15.2.4",
        "@angular-devkit/core": "~15.1.0",
        "@angular-devkit/schematics": **"~15.1.0",
        "@angular/cli": "~15.2.0",
         "@angular/compiler-cli": "15.2.5"
       }
```

**Comment by SergeyPl4ik** [comment]
I got the same issue after upgrading to the latest @ngxs/store (3.8.0) and angular 15

**Comment by gromon42** [comment]
Same issue happened here when trying to update my codebase to angular 15. 

I have been using the latest versions i.e : 

```
  "dependencies": {
    "@angular-ru/cdk": "^14.10.1",
    "@angular-ru/ngxs": "^14.1.1",
    }
```

**Comment by gromon42** [comment]
After some investigation, you need to update `@ngxs/store` dependencies to `3.8.0` to fix the issue since they have handled it on their part. I am opening a pull request if you want.

**Comment by bphkns** [comment]
It's working now
