### ISSUE TITLE
🐞 - `@angular-ru/cdk` peer dependencies are not listed

### ISSUE THREAD

**Issue by hakimio** [Angular-RU/angular-ru-sdk#1518]
### Which @angular-ru/* package(s) are the source of the bug?

cdk

### Is this a regression?

No

### Description

`@angular-ru/cdk` requires `@angular/material` but it's not listed in peer dependencies. Results in runtime error if you don't use the material library.

Tested in `Angular 17` with the new Angular app builder.

**Comment by hakimio** [comment]
@splincode there are very few places where `@angular/material` is used and its usage seems non-essential. 
What do you think about removal of the dependency entirely?

**Comment by splincode** [comment]
@hakimio no problem

**Comment by hakimio** [comment]
@splincode #1519

**Comment by hakimio** [comment]
@splincode thank you for merging the PR 🙂
