### ISSUE TITLE
🐞 - `@angular-ru/ngxs` is not compatible with `@ngxs/store` `v18`

### ISSUE THREAD

**Issue by hakimio** [Angular-RU/angular-ru-sdk#1525]
### Which @angular-ru/* package(s) are the source of the bug?

ngxs

### Is this a regression?

No

### Description

Try to use `@angular-ru/ngxs` with the newly released `@ngxs/store` `v18`.
Angular app compilation fails with the following errors:
```
X [ERROR] TS1238: Unable to resolve signature of class decorator when called as an expression.
  Type 'typeof CountryRepository' has no properties in common with type 'DataStateClass<any, any>'. [plugin angular-compiler]

    src/app/pages/countries/+state/country.repository.ts:8:1:
      8 │ @StateRepository()
        ╵  ~~~~~~~~~~~~~~~~~

```

**Comment by splincode** [comment]
I don't have time to support that repository, sorry

**Comment by hakimio** [comment]
That's fine. I'll look into it when I have time.

**Comment by splincode** [comment]
Thank you

**Comment by hakimio** [comment]
@splincode @Markiewic  to make `@angular-ru/ngxs` compatible with `@ngxs/store` `v18`, I would need to update angular to `v16`. Is that ok?

**Comment by splincode** [comment]
Sure, you can upgrade to Angular 16

**Comment by hakimio** [comment]
@splincode which commit fixed the issue?

**Comment by hakimio** [comment]
The new packages seem to be missing peer dependencies.

**Comment by splincode** [comment]
fixed

**Comment by hakimio** [comment]
Shouldn't there also be some minimum requirement for Angular and related packages (forms, cdk, router, etc)? Is it Angular `16` or `18`?

**Comment by splincode** [comment]
I don't want to add this
