### ISSUE TITLE
🐞 - `@StateRepository` decorator error when used with `@ngxs/store` `v18.1.3`

### ISSUE THREAD

**Issue by hakimio** [Angular-RU/angular-ru-sdk#1526]
### Which @angular-ru/* package(s) are the source of the bug?

ngxs

### Is this a regression?

Yes

### Description

After upgrading `@ngxs/store` from `18.1.1` to `18.1.3`, TS reports error:
```
TS1238: Unable to resolve signature of class decorator when called as an expression.
Type 'typeof FooRepository' has no properties in common with type 'DataStateClass'.
```

![image](https://github.com/user-attachments/assets/18886ea6-df15-4021-8f99-6ef3879e3578)

**Comment by splincode** [comment]
Could you fix it?

**Comment by hakimio** [comment]
Ok, I'll try.

**Comment by hakimio** [comment]
This time it's not only type changes but also some bigger changes like the following:
- https://github.com/ngxs/store/pull/2219
- https://github.com/ngxs/store/pull/2224

It will take some time to fix this.
