### ISSUE TITLE
New API for ngx-table-builder

### ISSUE THREAD

**Issue by splincode** [Angular-RU/angular-ru-sdk#506]
**Actual behaviour**

**Expected behaviour**

**Linked**

- [ ] https://github.com/Angular-RU/angular-ru-sdk/issues/498 Deep keys for exclude

**Comment by splincode** [comment]
- [ ] https://github.com/Angular-RU/angular-ru-sdk/issues/498

**Comment by splincode** [comment]
New editable context

```ts
 <ng-template ngx-td row let-row>
    <input ngxContentEdit 
        [ngMode]="row.cost" (ngModelChange)="asyncUpdate(...)" />

    <span ngxContentPreview>{{ row.cost | currency: 'USD' }}</span>
 </ng-template>

```

**Comment by Schirbak** [comment]
+ automatically provide tab indexes into cells
+ focus ngxContentEdit input automatically by tab index
